version: '3.5'
services:
  db_pg:
    image: postgres:latest
    restart: always
    ports:
      - "5432"
    volumes:
      - ./postgres-data/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test123
      POSTGRES_DB: SIHA_postgres

  flask:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db_pg
    #command: ["./wait-for-postgres.sh", "db_pg", "python", "app.py"]
  
  